42ity/fty-common

- builds/check_zproject/ci_build.sh
- ci_build.sh
- project.xml
Solution : use release tag instead of add the branch in the repository tag
>  Problem : project.xml do not use release propeties

- src/fty-common/log/fty_log.cc
Signed-off-by: Daviet, Nicolas <NicolasDaviet@eaton.com>
> Problem : After delete, pointer not set to NULL

- .gitignore
- README.md
- include/fty-common/log/fty_log.h
- src/fty-common/db/dbpath.cc
- src/fty-common/log/fty_log.cc
Solution : Use object instead of pointer
> Problem : In some cases, agent can't delete the ftylog object

- include/fty-common/log/fty_log.h
- src/fty-common/log/fty_log.cc
- src/fty-common/web/utils_web.cc
> Problem : We need some utilities fct

- include/fty-common/log/fty_log.h
- src/fty-common/log/fty_log.cc
Signed-off-by: Daviet, Nicolas <NicolasDaviet@eaton.com>
> Problem : variadic functions crash for C code

- include/fty-common/log/fty_log.h
> Problem: ecpp compiler add some nasty log_define

- .gitignore
- .travis.fixsasl
- .travis.yml
- Jenkinsfile
- Makefile.am
- ci_build.sh
- configure.ac
- include/fty_common_library.h
- packaging/debian/control
- packaging/debian/fty-common.dsc.obs
- packaging/redhat/fty-common.spec
- project.xml
- src/Makemodule.am
- src/fty_common_classes.h
- src/fty_common_private_selftest.cc
- src/fty_common_selftest.cc
- src/libfty_common.pc.in
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
> Problem: sasl depencies are missing

- src/fty-common/web/sasl.cc
Solution: include the header that should have it
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
> Problem: writev not defined in this scope

- include/fty-common/web/helpers.h
> Problem: We need reauth flag on UserInfo

- src/fty-common/log/fty_log.cc
Solution : 
At start load default consoleappender.
And if the path to the log configuration file is correct, load the log configuration file
> Problem : Log4cplus error when start default ftylog object

- install.xml
- packaging/debian/libfty-common1.postinst
- src/fty-common/web/tokens.cc
- src/fty-common/web/utils_web.cc
- src/fty-session.cfg
> Problem: we want to be able to change the session timeout

- include/fty-common/common/fty_uuid.h
- src/fty-common/common/fty_uuid.cc
> Problem: We need to create uuid based on our requirements

- include/fty-common/common/fty_uuid.h
- project.xml
- src/fty-common/common/fty_uuid.cc
- src/fty_common_selftest.cc
> Problem: We want to turn seftest on

- include/fty-common/common/fty_uuid.h
- src/fty-common/common/fty_uuid.cc
> Problem: Need to change char to const char

- include/fty-common/log/fty_log.h
- src/fty-common/log/fty_log.cc
Signed-off-by: Millieret, Xavier <XavierMillieret@Eaton.com>
> Adding set and clear context (MDC)

- .gitignore
- .travis.yml
- Makefile.am
- builds/check_zproject/ci_build.sh
- ci_build.sh
- configure.ac
- include/fty_common_library.h
- packaging/debian/rules
- packaging/redhat/fty-common.spec
- project.xml
- src/libfty_common.pc.in
> Regen for no "lib"tntnet, and *require* the dependency

- src/fty-common/web/helpers.cc
> Problem : asset_name must allow almost all characters

- src/fty-common/web/helpers.cc
Solution: List etn-licensing / licensing agent
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
> Problem: Need to allow licensing agent systemctl

- src/fty-common/web/helpers.cc
Solution: List etn-licensing / licensing agent
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
(cherry picked from commit acb39f3710146907afac02a3ec1d82079230ac7a)
> Problem: Need to allow licensing agent systemctl (1.4)

- src/fty-common/web/helpers.cc
> Problem: nonexisting service is restarted for etn-licensing

- src/fty-common/web/utils_web.cc
> Problem: We want an access for advanced configuration of fty-discovery

- src/fty-common/web/audit_log.cc
because was not accessible for c interface
Solution: fixed
> Problem: default log configuration renamed,

- include/fty_common_asset_types.h
- src/fty_common_asset_types.cc
> Problem: some conversion functions missing

- include/Makefile.am
- include/fty_common_agents.h
- include/fty_common_library.h
- packaging/debian/control
- project.xml
- src/fty_common_classes.h
- src/fty_common_selftest.cc
Solution: Create a central point for agents name
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
> Problem: Agents name are scattered and redundant

- include/fty_common_filesystem.h
- src/fty_common_filesystem.cc
Solution: is_file_in_directory, is_item_in_directory added
> Problem: filesystem fun for fty-nut missing

- include/fty_common_agents.h
Solution: Add a note
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
> Problem: Agent tpower has 2 names

- include/fty_common_agents.h
> Problem: Agent names do not correspond to Malamute adresses.

- README.md
> Problem: add list of headers to README

- include/fty_common_macros.h
> Problem: we need translation macro to mark strings processed by lua

- include/fty_common_utf8.h
- src/fty_common_utf8.cc
> (M/M) We need JSON-escaping code to be accesible from every component.

- include/fty_common_utf8.h
> Fix travis.

- include/fty_common_utf8.h
- src/fty_common_utf8.cc
Solution: Implement it as a variadic functions, which for each argument, adds JSON entry and rewrites the key accordingly.
> (M/S)Problem: We need a function to transform translation strings into JSON.

- include/fty_common_macros.h
Solution: Make TRANSLATE_ME call function which converts translation strings to JSON.
Signed-off-by: Jana Rapava <JanaRapava@eaton.com>
> (XS/L) Problem: We need to jsonify translation strings.

- include/fty_common_utf8.h
> (S/M) Problem: We need to use correct includes in C and C++ version.

- src/fty_common_utf8.cc
Solution: Update code and tests.
> Problem: Changed variable designator.

- include/fty_common_macros.h
- include/fty_common_utf8.h
- src/fty_common_utf8.cc
Signed-off-by: Jana Rapava <JanaRapava@eaton.com>
> Add jsonify function which takes va_list.

- src/fty_common_utf8.cc
Solution: Add a check for this case.
> (S/L) Problem: We jsonify JSON string unnecessarily.

- include/fty_common_json.h
- project.xml
- src/fty_common_json.cc
- src/fty_common_selftest.cc
Solution: fixed ignored {{ when searching for json object, added unit tests
> Problem: missing unit tests, ignored starting {{ when searching for json object

- src/fty_common_utf8.cc
Solution: Remove quotes before they are escaped and in a cycle with correct start/end points.
> (L/L) Problem: All levels of nesting do not work correctly.

- src/fty_common_utf8.cc
> (S/S) Improve exception handling.

- src/fty_common_utf8.cc
Solution: improved formatting recognition
Also added some whitespaces before brackets
> Problem: formatting string end is not properly recognized and some weird data are then passed

- src/fty_common_utf8.cc
Solution: Search for any match.
> (S/M) Problem: Removal of closing quotes searches only for the first match.

- .travis.yml
- ci_deploy_obs.sh
- configure.ac
- project.xml
- src/Makemodule.am
- src/fty_common_classes.h
- src/libfty_common.pc.in
> Regenerated zproject

- include/fty_common_client.h
> Fix pedentic issue

- include/Makefile.am
- include/fty_common_library.h
- project.xml
- src/Makemodule.am
- src/fty_common_selftest.cc
> HOTFIX fix project xml by putting interface stable

- src/fty_common_unit_tests.cc
> Make global variables static

- include/fty_common_unit_tests.h
- src/fty_common_unit_tests.cc
> Add a function to get the last sender in the EchoServer use for unit tests

- Makefile.am
- builds/check_zproject/ci_build.sh
- ci_build.sh
- configure.ac
- include/fty_common_json.h
- include/fty_common_library.h
- packaging/debian/control
- packaging/debian/fty-common.dsc.obs
- packaging/redhat/fty-common.spec
- project.xml
- src/fty_common_json.cc
- src/selftest-ro/example.json
Solution: do it
* cxxtools JSON serializer/parser simple interface
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
> Problem: need a common cxxtools JSON serializer/parser simple interface

- include/fty_common_str_defs.h
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
> Fix header guard

- include/fty_common_asset_types.h
- src/fty_common_asset_types.cc
- src/fty_common_base.cc
Solution: do the best
* rewriting (sub)type conversions to (sub)typeid
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
> Problem: asset type / subtype support is a mess

- include/fty_common_asset_types.h
- src/fty_common_base.cc
* new indexes
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
> cops/pcu ids have changed (DB init, fty-core)

- Jenkinsfile
- include/fty_common_asset_types.h
- src/fty_common_asset_types.cc
- src/fty_common_base.cc
- src/fty_common_utf8.cc
- new cops declaration
- enforce get ID/name (use a unique map instead of two vectors)
- unit tests (non reg)
> integration of Featureimage/powerchain analysis

- include/fty_common_asset_types.h
- src/fty_common_asset_types.cc
- src/fty_common_base.cc
Updated according to latest DB content
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
> Update types/subtypes to match database content

- include/fty_common_asset_types.h
- src/fty_common_asset_types.cc
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
> Add DELL_VXRAIL_EXSI device subtype
